services:
  - type: web
    name: syn-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m alembic upgrade head
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: syn-db
          property: connectionString

databases:
  - name: syn_db
    databaseName: syndb
    user: syn
