"""notification and event models added

Revision ID: 0163a6badd45
Revises: 9137f614affc
Create Date: 2024-12-13 09:41:57.805814

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0163a6badd45"
down_revision: Union[str, None] = "9137f614affc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("title_template", sa.String(), nullable=False),
        sa.Column("message_template", sa.String(), nullable=False),
        sa.Column(
            "priority",
            postgresql.ENUM(
                "HIGH", "NORMAL", "LOW", name="notificationpriority", create_type=False
            ),
            nullable=False,
            server_default="NORMAL",
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "notification_type",
            postgresql.ENUM(
                "ANNOUNCEMENT",
                "SCHEDULE_CHANGE",
                "SHIFT_TRADE",
                "LEAVE_REQUEST",
                "SYSTEM",
                name="notificationtype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("email_enabled", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_preferences_user_id", "notification_preferences", ["user_id"]
    )
    op.create_index(
        "ix_notification_templates_event_type", "notification_templates", ["event_type"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_preferences")
    op.drop_table("notification_templates")
    # ### end Alembic commands ###
