"""notification models added

Revision ID: 28d2987bfbbe
Revises: a9d58b7e3a87
Create Date: 2024-12-14 20:54:37.119087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28d2987bfbbe'
down_revision: Union[str, None] = 'a9d58b7e3a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'READ', name='notificationstatus'), nullable=True))
    op.add_column('notifications', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('next_retry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'read_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'error_message')
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'next_retry')
    op.drop_column('notifications', 'retry_count')
    op.drop_column('notifications', 'status')
    # ### end Alembic commands ###
