"""adeed_comment_in_user_model

Revision ID: 80c5cf497bb8
Revises: 21df64346dee
Create Date: 2024-12-19 23:19:33.726045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c5cf497bb8'
down_revision: Union[str, None] = '21df64346dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'comment')
    # ### end Alembic commands ###
