"""Notification model updated

Revision ID: 9137f614affc
Revises: 7dd991ca98ae
Create Date: 2024-12-12 22:42:45.962159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9137f614affc'
down_revision: Union[str, None] = '7dd991ca98ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcements', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('announcements', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('priority', sa.Enum('HIGH', 'NORMAL', 'LOW', name='notificationpriority'), nullable=True))
    op.add_column('notifications', sa.Column('data', sa.JSON(), nullable=False))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('SCHEDULE', 'ANNOUNCEMENT', 'REQUEST', name='notificationtype'),
               nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('SCHEDULE', 'ANNOUNCEMENT', 'REQUEST', name='notificationtype'),
               nullable=True)
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'data')
    op.drop_column('notifications', 'priority')
    op.drop_column('notifications', 'title')
    op.alter_column('announcements', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('announcements', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
