"""add is_demo to user model

Revision ID: bac2490fb76a
Revises: dd2931147cac
Create Date: 2024-12-22 12:42:42.129358

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bac2490fb76a"
down_revision: Union[str, None] = "dd2931147cac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_demo", sa.Boolean(), nullable=True))


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_demo")


# ### end Alembic commands ###
